[project]
name = "palimpsest"
version = "0.1.0"
description = "Preserve your AI development workflows. Their model, your code, your work."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

